@startuml Hilo Game Design 
!define DARKRED
!includeurl https://raw.githubusercontent.com/Drakemor/RedDress-PlantUML/master/style.puml

package main {

    class Director {
        - bool _is_playing
        - string _guess

        - jumper: Jumper
        - puzzle: Puzzle
        - terminal_service: TerminalService

        + start_game()
        - _get_inputs()
        - _do_updates()
        - _do_outputs()
    }

    class Jumper {

        - list _image
        - bool _alive


        - _display()
        - _remove()
        - _check()

    }

    class Puzzle {

        - list _word
        - list _blanks 
        
        - _choose_word()
        - _display()
        - _replace()
        - _check()
        

    }

    class TerminalService {

        + read_number()
        + read_text()
        + write_text()

    }

    Jumper -> Director
    TerminalService -> Director
    Puzzle -> Director


    note bottom of TerminalService
    All three functions will have a string argument.
    end note

    note top of Puzzle
    The Puzzle class will display the blank spaces and letters.
    It will also check the players guess and replace the
    blank spaces with letters when guessed right.
    end note

    note bottom of Jumper
    The Jumper class will display the Parachute. It will also
    check to see if all the pieces for the parachute are
    gone.
    end note

    note top of Director
    The Director class will manage the game flow and use the other 
    3 classes in running the game.
    end note

}


@enduml